# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: webmenow/tonavantage
  branch: main
  base_url: https://sveltia-cms-auth.sergei-shevchenko.workers.dev/

media_folder: /media
# public_folder: /media

collections:
  - name: content
    label: Content
    folder: /
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

# https://sveltiacms.app/en/docs/start#manual-installation
